### ISSUE TITLE
Issue with the static trajectory generation 

### ISSUE THREAD

**Issue by janhavi19** [kjyv/FloBaRoID#10]
As the trajectory generation does not provide a feasible solution , I tried out the static trajectory generation I am getting following error can you help me out .

SDP found std solution with 0.0968628270356 squared residual error
Objective function value: 0.000390542557771 (last best: inf)
(Gradient evaluation)
Parameter error: [  8.22906798e-03   1.11528984e-04   2.00252935e-04  -1.97377992e-05   2.64326747e-03  -8.39580773e-03   2.14005092e-03  -1.73155946e-03  -6.80186293e-05
   7.80794591e-04  -1.21921512e-02   9.40503509e-03]
Constraints not met.

and finally there is no feasible solution again

**Comment by kjyv** [comment]
It is possible that some of your installed libraries are not the proper versions, especially pyOpt. Also, I have not used the code in a while and can't guarantee it is still working on newer versions of the dependencies. It is possible that your model description or configuration files need to be changed so this works. The config options allow many different ways of tweaking the trajectory optimization, some of which won't work together. As I don't know what options you have set and what model you are using, I can't say why it doesn't work. Also, this is not a support forum and I won't do debugging for you. Consider this software as collection of implementations. It is not a black box solution that works in all cases. You might have to understand the algorithms and theory behind it a bit more in order to make use of it.
