### ISSUE TITLE
module 'idyntree.bindings' has no attribute 'DynamicsRegressorGenerator'

### ISSUE THREAD

**Issue by chouweixin** [kjyv/FloBaRoID#15]
I install the Python library with via [conda-forge] using the following command

conda install -c conda-forge idyntree
and have replaced import iDynTree; iDynTree.init_helpers(); iDynTree.init_numpy_helpers() with import idyntree.bindings as iDynTree, the python vesrion is 3.6.15, the idyntree vesrion is 4.0.0
![11](https://github.com/kjyv/FloBaRoID/assets/74995767/ccf3a8bd-7dc7-4fcc-9299-909288205983)
![22](https://github.com/kjyv/FloBaRoID/assets/74995767/c534bd41-5926-47d1-b3d1-89d9e15d0835)

**Comment by chouweixin** [comment]
I installed the latest version of iDynTree, but this is  incompatibility with the need repo.

**Comment by traversaro** [comment]
Hello @chouweixin, iDynTree mantainer here. The `DynamicsRegressorGenerator` class was removed in iDynTree 2.0.0 as it was using the `IDYNTREE_USES_KDL` option, see https://github.com/robotology/idyntree/releases/tag/v2.0.0 . I guess you can obtain similar functionalities by using the [`idyntree.bindings.ModelLoader`](https://robotology.github.io/idyntree/classiDynTree_1_1ModelLoader.html) class to load the class and the [`idyntree.bindings.KinDynComputations. inverseDynamicsInertialParametersRegressor`](https://robotology.github.io/idyntree/classiDynTree_1_1KinDynComputations.html#a2945d5222c617680fc262ae01dca0f23) to compute the regressor.

**Comment by kjyv** [comment]
Hey @chouweixin (and @traversaro!),

Many packages have changed quite a bit since I've worked on this and no one actively maintains this repo. To get it working as is, you might want to start with using the versions that are mentioned in the readme as minimum versions (basically what was current 2018). Sorry that there is no explicit version pinning.
Pull requests very welcome!
